### ISSUE TITLE
evil-mode troubles

### ISSUE THREAD

**Issue by tgbugs** [Alexander-Miller/cfrs#3]
If you use this with evil mode enabled globally the new frame defaults to normal mode so you can't start typing and if you accidentally tab out of the window you can never select the subframe again and have to terminate the program to start over. Not sure if there is a way to set the new frame defaults so that it isn't captured by things like that.

**Comment by Alexander-Miller** [comment]
Putting things into insert-mode is easy enough.

For the focus issue I'll have to think of something.

**Comment by Alexander-Miller** [comment]
Insert state is now default when available and the input frame can be focused again properly (you could actually do so before, it just didn't look like you could because the cursor didn't change).
