### ISSUE TITLE
Not accepting input in emacs-master feature/pgtk+feature/native-comp

### ISSUE THREAD

**Issue by dinkonin** [Alexander-Miller/cfrs#4]
Hello , 
I'm using emacs on arch compiled from [AUR](https://aur.archlinux.org/packages/emacs-pgtk-native-comp-git/).
When using cfrs the childframe displays but does not accept any input and appears stuck on the screen. I'm not really sure whether  to report this here or to emacs bug mailing list.

Here's a video of the observed behaviour started with `emacs -Q`:

https://user-images.githubusercontent.com/12976386/103913580-5d819780-5111-11eb-9815-66e748c9a5d2.mp4

**Comment by Alexander-Miller** [comment]
If this a general problem then you'll probably have the same issue with other posframe packages ivy-posframe. So firs let's try using the bare emacs api:

```Elisp
(let* ((window
        (display-buffer-in-child-frame
         (get-buffer-create "*TEST*")
         `((child-frame-parameters
            .
            ((left . 100)
             (top  . 100)
             (height . 1)
             (width . 50)
             (minibuffer . nil)
             (menu-bar-lines . 0)
             (tool-bar-lines . 0)
             (line-spacing . 0)
             (unsplittable . t)
             (no-special-glyphs . t)
             (undecorated . t)
             (no-accept-focus . nil)
             (internal-border-width . 2)
             (horizontal-scroll-bars . nil))))))
       (frame (window-frame window)))
  (x-focus-frame frame))
```

That should popup a child frame you can edit. If that does work we'll try posframe next:

```Elisp
(x-focus-frame
 (posframe-show
  (get-buffer-create "*TEST*")
  :min-height 1
  :min-width 40
  :string "test"
  :override-parameters `((cursor . ,cursor-type)
                         (no-accept-focus . nil))))
```

If either of these doesn't work then the cause is somewhere upstream.

> Here's a video of the observed behaviour started with emacs -Q:

Can't watch that, my browser says the file is corrupt.

**Comment by dinkonin** [comment]
Same behaivour with the above two code blocks.

I'm sorry about the broken video , I hava changed my  screen recording software.
Do these videos highlighting the problem  display properly:

https://user-images.githubusercontent.com/12976386/104011124-4ba60000-51b6-11eb-9df6-302f710d60ff.mp4


https://user-images.githubusercontent.com/12976386/104011129-4e085a00-51b6-11eb-8ec6-ef5631bcb141.mp4

**Comment by Alexander-Miller** [comment]
The videos work now. That is a general problem with the behavior of child frames, so it's out of my hands now. You should report it with the pgtk upstream (I am using the nativecomp branch myself without issue, so pgtk is the obvious culprit here).

**Comment by eeshugerman** [comment]
I have this issue too, both in treemacs and with the code blocks above. What's odd though is I use ivy-posframe and which-key-posframe without issue. Perhaps they employ some kind of workaround? (IIRC one is based directly on the other.)

Also, anyone know where to file bugs for pgtk emacs?

**Comment by Alexander-Miller** [comment]
> What's odd though is I use ivy-posframe and which-key-posframe without issue.

Then I should have a look at what posframe gets up to.

> Also, anyone know where to file bugs for pgtk emacs?

I've seen some development-related discussion on emacs-devel, so I guess you could ask around there.

**Comment by edrex** [comment]
> Also, anyone know where to file bugs for pgtk emacs?

I believe the upstream branch is still being developed so probably there:

This is the PR that implemented posframe: https://github.com/masm11/emacs/pull/15
